import Head from 'next/head';
import About from '../src/layouts/About';
import Describe from '../src/layouts/Describe';
import Hero from '../src/layouts/Hero';
import Progress from '../src/layouts/Progress';
import Projects from '../src/layouts/Projects';
import Skills from '../src/layouts/Skills';
import Testimonial from '../src/layouts/Testimonial';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Abdul Malik</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Hero />
        <Describe />
        <Projects />
        <Testimonial />
        <Progress />
        <Skills />
        <About />
      </main>
    </div>
  );
}
// export const getStaticProps =
